### ISSUE TITLE
Persist level and current xp in data base

### ISSUE THREAD

**Issue by Maxopoly** [Maxopoly/SkilUp#1]
A plugin instance has multiple skills and each skill has a PlayerXPStatus for every player currently on the server. The only data needed to reconstruct a PlayerXPStatus is the name of the skill as an identifier, the UUID of the player, his currently level and his current XP. 

When saving just iterate over the skills and save the combination of skill name, UUID, current XP and level.
Methods to roughly outline how it should work are already here: https://github.com/Maxopoly/SkilUp/blob/master/src/com/github/maxopoly/SkilUp/SkilUpManager.java

@rourke750 Could you do this?

**Comment by rourke750** [comment]
Sure, might only get two it on wednesday.  Have some class work due one monday and tuesday and need to be working on that.

**Comment by Maxopoly** [comment]
Yeah dont worry, it's not super urgent.

**Comment by Maxopoly** [comment]
> Sure, might only get two it on wednesday.
